### ISSUE TITLE
Create separate binary for imgui healthcheck

### ISSUE THREAD

**Issue by Glebanister** [PlatformerTeam/mad#17]

**Comment by Mirong1707** [comment]
Не очень понял что это за таска. Я в test добавил два дефайна. По дефолту будет просто проверяться, что все 3 библиотеки подключены(иначе не скомпилится). Если раскомментить один из дефайнов, то будет выводится какое-то из двух тестовых окон(для imgui и box2d соответственно)

**Comment by Mirong1707** [comment]
запушил в pr ImguiSfml
