### ISSUE TITLE
Implement Camera

### ISSUE THREAD

**Issue by Glebanister** [PlatformerTeam/mad#40]
- [x] handle(cosnt Event&)
- [x] render()
- [x] Implement TrueFilter (filters nothing)
- [x] Implement LambdaIntent
- [x] Should contain `ShPtr<World>` and send LambdaIntent to see all entities (call appear method)

**Comment by Alexeyha** [comment]
Add Position struct or store the position in the Image (another class) (?)

**Comment by Alexeyha** [comment]
What events are processed? Only Visual?

**Comment by Glebanister** [comment]
Position == fvec2d

**Comment by Glebanister** [comment]
Yes (да)
Ну то есть какие ещё события нужно обрабатывать камере?) потом если что
добавим другие
