### ISSUE TITLE
Decide about physics engine

### ISSUE THREAD

**Issue by Glebanister** [PlatformerTeam/mad#5]
We need to decide, will we use our physics engine or someone else's and add it as a dependency to our project.

- [x] Study existing 2 dimensional physics engines
- [x] Choose one
- [x] Add this physics engine as a submodule to our project (we probably should put all dependencies into the `./deps` directory)
- [x] Study a bit how to work with this engine. We need it to know, how to integrate this engine into our architecture (#2)
- [x] Integrate their cmake project into ours (person which solves #3 may help)
- [x] Add build some demo executable in the `./tests` directory, which briefly tests the functionality of the physics engine

**Comment by Mirong1707** [comment]
что именно требуется от тестов на данном этапе? Проверить что библиотека просто подключена, мол можем инициализировать что-то из неё?

**Comment by Glebanister** [comment]
@Mirong1707 да, просто что всё работает. В качестве теста - просто отдельный исполняемый файл в тестах, который не прилинкован к core и gtest, но который запускает box2d
