### ISSUE TITLE
Create Collision event

### ISSUE THREAD

**Issue by Glebanister** [PlatformerTeam/mad#73]
- [x] Create Collision event type
- [x] Create Collision event (which has ids of collided bodies and some other related info)
- [ ] Create collision.cpp executable in the `./game/` with a SequentialRunner and collision handler
- [ ] Change color of collided blocks when they collide in the handler, or do something more fun

**Comment by Mirong1707** [comment]
прелагаю закрывать ишью, красить буду сейчас уже при ударе моба
